
server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hls?useSSL=false&amp
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: com.tsc.mybatis.Pojo
pagehelper:
  dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
