
server:
  port: 10010
spring:
  application:
    name: api-gateway
zuul:
  routes:
    service-provider: /service-provider/** # 这里是映射路径
    service-consumer: /service-consumer/**
  prefix: /api
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka,http://localhost:10087/eureka
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000 # 设置hystrix的超时时间为6000ms