server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybites?useSSL=true
    username: root
    password: 123456
mybatis:
  type-aliases-package: com.tsc.service.pojo
logging:
  level:
    root: debug